site_name: 北京明学思机器人科技有限公司

site_url: https://mxsrobot.com
site_description: Project documentation with Markdown.
site_author: XueYuSky


theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
  - 首页: index.md
  - 页面2: post/doc2.md
  - 使用帮助: post/doc3.md